  $(function() {
    $('#sendForm').on('click', 'button', function(e) {
      e.preventDefault();
  
      var $form = $("#sendForm");
      
      var responsavel = document.querySelector('#responsavel').value;
      var data = document.querySelector('#data').value;
      var dataf = new Date(data);
      var dataformatada = dataf.toLocaleDateString('pt-BR', {timeZone: 'UTC'});
      var turno = document.querySelector('#turno').value;
      var horaTurno = document.querySelector('#horaTurno').value;
      var qtdToretePinus = document.querySelector('#qtdToretePinus').value;
      var tnToretePinus = document.querySelector('#tnToretePinus').value;
      var qtdToreteEuca = document.querySelector('#qtdToreteEuca').value;
      var tnToreteEuca = document.querySelector('#tnToreteEuca').value;
      var totalQtd = parseInt(qtdToretePinus) + parseInt(qtdToreteEuca);
      var totalTn = parseFloat(tnToretePinus) + parseFloat(tnToreteEuca);
      totalTn = totalTn.toFixed(2);
      var qtdCavacoPinus = document.querySelector('#qtdCavacoPinus').value;
      var tnCavacoPinus = document.querySelector('#tnCavacoPinus').value;
      var qtdCavacoEuca = document.querySelector('#qtdCavacoEuca').value;
      var tnCavacoEuca = document.querySelector('#tnCavacoEuca').value;
      var qtdCavacoCelulose = document.querySelector('#qtdCavacoCelulose').value;
      var tnCavacoCelulose = document.querySelector('#tnCavacoCelulose').value;
      var qtdTransbordoTurno = document.querySelector('#qtdTransbordoTurno').value;
      var tnTransbordoTurno = document.querySelector('#tnTransbordoTurno').value;
      var qtdTransbordoDia = document.querySelector('#qtdTransbordoDia').value;
      var tnTransbordoDia = document.querySelector('#tnTransbordoDia').value;
      var filaInterna = document.querySelector('#filaInterna').value;
      var filaExterna = document.querySelector('#filaExterna').value;
      
      
      var msg = "https://api.whatsapp.com/send?text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
      //var msg = "whatsapp://send?text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
      /*
      switch (responsavel) {
        case 'DANILO':
          var msg = "https://api.whatsapp.com/send?phone=5515997876098&text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
          break;
        case 'DIEGO':
          var msg = "https://api.whatsapp.com/send?phone=5515997920740&text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
          break;
        case 'JACONIAS':
          var msg = "https://api.whatsapp.com/send?phone=5515998027236&text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
          break;
        case 'JAIRO':
          var msg = "https://api.whatsapp.com/send?phone=5515998169620&text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
          break;
        case 'REGINALDO':
          var msg = "https://api.whatsapp.com/send?phone=5515997703458&text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
          break;
        case 'RICARDO':
          var msg = "https://api.whatsapp.com/send?phone=5515997511084&text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
          break;
        case 'THIAGO':
          var msg = "https://api.whatsapp.com/send?phone=5515997195339&text=*UPDATE%20-%20Recebimento%20de%20Madeiras*%0A_" + dataformatada + "_%0A_Turma%20" + turno + "%20das%20" + horaTurno +"_%0A--------------------------------------------------------------------%0A*Toretes*%0A✓%20" + qtdToretePinus + "%20cargas%20de%20pinus%20=%20" + tnToretePinus + "%20tn%0A✓%20" + qtdToreteEuca + "%20cargas%20de%20euca.%20=%20" + tnToreteEuca + "%20tn%0A_*Total:%20" + totalQtd + "%20cargas%20=%20" + totalTn + "%20tn*_%0A--------------------------------------------------------------------%0A*Cavaco*%0A✓%20Pinus/Serraria:%20" + qtdCavacoPinus + "%20cargas%20=%20" + tnCavacoPinus + "%20tn%0A✓%20Eucalipto:%20" + qtdCavacoEuca + "%20cargas%20=%20" + tnCavacoEuca + "%20tn%0A✓%20Celulose:%20" + qtdCavacoCelulose + "%20cargas%20=%20" + tnCavacoCelulose + "%20tn%0A--------------------------------------------------------------------%0A*Transbordo*%0A✓%20Turno%20" + turno + ":%20" + qtdTransbordoTurno + "%20cargas%20=%20" + tnTransbordoTurno + "%20tn%0A✓%20Dia:%20" + qtdTransbordoDia + "%20cargas%20=%20" + tnTransbordoDia + "%20tn%0A--------------------------------------------------------------------%0A*Fila*%0AInterna:%20" + filaInterna + "%0AExterna:%20" + filaExterna + "%0A%0A_*Responsável:*%20" + responsavel + "_";
            break;
        case 'Selecione...':
          alert("Selecione o responsavel.");
            break;
      }
      */

      $form.attr('action', msg);
      $form.submit();
    });
  });
